practice-app/front-end/about.html
=> #82 Update front-end

practice-app/react-front-end/src/App.js, practice-app/react-front-end/src/service/authentication.service.js, practice-app/react-front-end/src/service/profileinformation.service.js, practice-app/react-front-end/src/utils/auth-header.js, practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js, practice-app/react-front-end/src/views/SignupPage/SignupPage.js
- Add new services that provide getting profile information and authentication mechanism.
- Fix the homepage.
=> Add new services, fix the link in homepage

practice-app/react-front-end/package-lock.json, practice-app/react-front-end/package.json, practice-app/react-front-end/src/App.js, practice-app/react-front-end/src/views/LoginPage/LoginPage.js
Google API login is ready. Please review & merge.
=> Google API ile login olma.

backend/tradersplatform/follow/views.py, backend/tradersplatform/myuser/serializers.py, backend/tradersplatform/myuser/urls.py, backend/tradersplatform/myuser/views.py
=> user upgrade & downgrade

practice-app/react-front-end/src/components/PrivateRoute.js, practice-app/react-front-end/src/components/ProfileHeader/PheaderLinks.js, practice-app/react-front-end/src/index.js, practice-app/react-front-end/src/service/authentication.service.js, practice-app/react-front-end/src/service/edit-profile-service.js, practice-app/react-front-end/src/service/registration.service.js, practice-app/react-front-end/src/utils/cookie.js, practice-app/react-front-end/src/utils/validator.js, practice-app/react-front-end/src/views/LoginPage/LoginPage.js, practice-app/react-front-end/src/views/ProfilePage/EditProfile.js, practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js, practice-app/react-front-end/src/views/SignupPage/SignupPage.js
Profile-page, profile-edit and articles pages are accessible only with the valid token.
=> Router authentication

practice-app/react-front-end/src/components/ProfileHeader/PheaderLinks.js, practice-app/react-front-end/src/index.js, practice-app/react-front-end/src/views/ArticlesPage/ArticlesPage.js, practice-app/react-front-end/src/views/PortfolioPage/Portfolio.js
- Route of Portfolio Page is protected. 
- Header added in Portfolio Page.
- Buttons are added in Articles Page.
- Small syntax error corrected.
=> PortfolioPage protected. Header and buttons added.

backend/tradersplatform/event/views.py
A request to /events should return a weekly calendar of events now. Please check if that works.
=> I have added event calendar feature

practice-app/react-front-end/src/components/Typography/Danger.js, practice-app/react-front-end/src/components/Typography/Info.js, practice-app/react-front-end/src/components/Typography/Muted.js, practice-app/react-front-end/src/components/Typography/Primary.js, practice-app/react-front-end/src/components/Typography/Quote.js, practice-app/react-front-end/src/components/Typography/Success.js, practice-app/react-front-end/src/components/Typography/Warning.js, practice-app/react-front-end/src/index.js, practice-app/react-front-end/src/views/ArticlesPage/Article.js
=> read more article added.

practice-app/react-front-end/src/index.js, practice-app/react-front-end/src/views/AddArticle/EditArticle.js, practice-app/react-front-end/src/views/AddArticle/section/Editing.js, practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js
=> edit article added.

practice-app/react-front-end/src/index.js, practice-app/react-front-end/src/service/article.service.js, practice-app/react-front-end/src/service/authentication.service.js, practice-app/react-front-end/src/service/user.service.js, practice-app/react-front-end/src/variables/general.js, practice-app/react-front-end/src/views/AddArticle/AddArticle.js, practice-app/react-front-end/src/views/AddArticle/EditArticle.js, practice-app/react-front-end/src/views/AddArticle/section/Adding.js, practice-app/react-front-end/src/views/AddArticle/section/Editing.js, practice-app/react-front-end/src/views/ArticlesPage/Article.js, practice-app/react-front-end/src/views/ArticlesPage/ArticlesPage.js, practice-app/react-front-end/src/views/LoginPage/LoginPage.js, practice-app/react-front-end/src/views/ProfilePage/ProfilePage.js, practice-app/react-front-end/src/views/ProfilePage/UserProfile.js, practice-app/react-front-end/src/views/WalletPage/WalletPage.js
=> Some modifications at wallet page.

practice-app/react-front-end/package-lock.json, practice-app/react-front-end/package.json, practice-app/react-front-end/src/components/ProfileHeader/PheaderLinks.js
=> search bar

android/khajit/app/src/main/java/com/project/khajit_app/activity/HomeFeedPageActivity.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/LoginPageActivity.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/editprofile/EditUserProfileFragment.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/other_profile/OtherUserProfile.kt
-Disable back button for login
-Refreshing profile page
=> Bug fixes and refreshing pages

practice-app/react-front-end/src/components/ProfileHeader/PheaderLinks.js, practice-app/react-front-end/src/index.js, practice-app/react-front-end/src/views/NotificationPage/Notification.js, practice-app/react-front-end/src/views/PortfolioPage/Notification.js
=> notifications page added.

backend/tradersplatform/article/urls.py, backend/tradersplatform/article/views.py
Now user can retrieve the articles which are related to the given search keyword.
=> Article Search

android/khajit/app/src/main/java/com/project/khajit_app/activity/DepositFundsFragment.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/editprofile/EditUserProfileFragment.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/mywallet/MyWalletFragment.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/mywallet/MyWalletFragmentModel.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/other_profile/OtherUserProfile.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/profile/UserProfile.kt, android/khajit/app/src/main/java/com/project/khajit_app/activity/ui/search/SearchFragment.kt, android/khajit/app/src/main/java/com/project/khajit_app/api/Api.kt, android/khajit/app/src/main/java/com/project/khajit_app/data/models/ArticleSearchModelResponse.kt, android/khajit/app/src/main/java/com/project/khajit_app/data/models/ArticleSearchResponse.kt, android/khajit/app/src/main/java/com/project/khajit_app/data/models/FollowingPendingListResponseModel.kt, android/khajit/app/src/main/java/com/project/khajit_app/data/models/FollowingPendingResponseModel.kt, android/khajit/app/src/main/java/com/project/khajit_app/data/models/ListEventResponse.kt, android/khajit/app/src/main/java/com/project/khajit_app/data/models/OneEventResponse.kt, android/khajit/app/src/main/java/com/project/khajit_app/data/models/createWalletResponse.kt, android/khajit/app/src/main/res/layout/fragment_deposit_funds.xml, android/khajit/app/src/main/res/layout/fragment_search.xml, android/khajit/app/src/main/res/layout/my_wallet.xml, android/khajit/app/src/main/res/layout/other_user_profile_fragment.xml
- User can search articles and events
- For private user follow requests, profile page screen changed and pending status added
- Wallet UI is added, user can see all its owned equipments, their prices and current wealths.
=> Search Events-Articles, Pending Request, Wallet

practice-app/react-front-end/src/components/ProfileHeader/PheaderLinks.js, practice-app/react-front-end/src/views/Equipment/Equipment.js
Necessary modifications were made.
=> Some changes in equipment page.

practice-app/react-front-end/src/views/Equipment/Equipment.js
Wrong currency symbol mentioned in the final milestone is corrected.
=> Currency symbol corrected.

backend/tradersplatform/article/views.py, backend/tradersplatform/article_comment/views.py, backend/tradersplatform/article_like/urls.py, backend/tradersplatform/article_like/views.py
1. Added 2 new endpoint for article like:
- is Article Liked By User
- is Article Disliked By User
2. Added list name to the responses that return list
2. Added filed name to the responses that return count
=> fix article, article comment, article like responses

backend/tradersplatform/article_like/views.py
=> bugfix - article like -dislike response

backend/tradersplatform/article/views.py
=> fix list article by user id response
